%% Bring everything in
names = {...
    'Ground_Truth_Treadmill1.csv'...
    'Ground_Truth_Treadmill2.csv'...
    'Ground_Truth_Treadmill3.csv'...
    'Ground_Truth_Treadmill5.csv'...
    };

%% Time Plots
figure
for i = 1:length(names)
    subplot(2,2,i)
    DataExaminer.plotTime(names{i},2);
    title(names{i})
end